# -----------------------------
# Material Theme Configuration
# ------------------------------
# red, pink, purple, deep purple, indigo, 
# blue, light blue, cyan, teal, green, light green, 
# lime, yellow, amber, orange, deep orange, brown, 
# grey, blue grey , black, white
#    primary: pink # teal
#    accent: indigo
#
# *** FONT ***
# Guide: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
# Google Fonts Supported: https://fonts.google.com/
#
# *** BLOG ***
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
# ---------------------------------

# Project information .........................................
site_name: "Learn With Markmaps"
site_url: https://nitya.github.io/learns-with-markmaps
site_author: Nitya Narasimhan
site_description: >-
  Explore various

# Repository ..................................................
repo_name: nitya/learns-with-markmaps
repo_url: https://github.com/nitya/alearns-with-markmaps

# Copyright ...................................................
copyright: >
  Copyright &copy; 2024 - present Nitya Narasimhan
  <br/>🍪 | <a href="#__consent">Change cookie settings</a>

# Configuration ...............................................
theme:
  name: material
  font:
    code: Roboto Mono  #Monospaced
    text: Roboto       #Regular
  logo: img/nitya-learns-ai.png
  language: en

  # Theme Modes ...............................................
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: black
      accent: pink
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to system preference 
  
  # Theme Features ...............................................
  features:
    - navigation.instant
    - navigation.expand             # sidebar collapsible sections open
    - navigation.instant.progress   # load progress indicator
    - navigation.tracking           # tracks anchor tags in URL
    - navigation.tabs               # tabbed on desktop, single in mobile    
    - navigation.tabs.sticky        # tabs stick when scrolling downtheme:
    - navigation.path               # add breadcrumbs
    - navigation.indexes            # default index.md in folder is section page
    - navigation.top
    - toc.follow
    - navigation.footer
    - content.code.copy             # allow copy-paste from codeblocks
    - content.tabs.link             # Ensures site-wide switch to same tab name

# Extras  ...............................................
extra:
  generator: false
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage 
  analytics:
    provider: google
    property: G-R6NWRNLWCZ

# Plugins  ...............................................
plugins:
  - search
  - markmap:
    # See: https://github.com/markmap/mkdocs-markmap
      base_path: docs
      encoding: utf-8
      file_extension: .mm.md

# Extensions  ...............................................
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      auto_title: true
      linenums: true
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

# Navigation  ...............................................
nav:
  - Markmaps:
    - index.md
    - azure-ai-foundry.md
    - bon-msignite-2024.md


